config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "ideas#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:index, :show, :edit, :update]
  resources :ideas, only: [:index, :new, :create, :destroy, :show] do
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :idea
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates :title, presence: true
  validates :info, presence: true
  validates :price, presence: true

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  has_many :comments

  def self.search(search)
    return Idea.all() unless search
    Idea.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :idea
  belongs_to :user
  validates_uniqueness_of :idea_id, scope: :user_id

  def already_liked?(idea)
    self.likes.exists?(idea_id: idea.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :ideas, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_ideas, through: :likes, source: :idea
  has_many :comments

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def already_liked?(idea)
    self.likes.exists?(idea_id: idea.id)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
    
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comments = Comment.all
    if @comment.save
      @comment = Comment.new
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, idea_id: params[:idea_id])
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  # before_action :move_to_index, except: [:index, :show]
  def index
    require 'net/http'
    require 'json'

    @url = 'http://weather.livedoor.com/forecast/webservice/json/v1?city=270000'
    @uri = URI(@url)
    @response = Net::HTTP.get(@uri)
    @output = JSON.parse(@response)
    
    @city_telop = @output['forecasts'][0]['telop']

    @ideas = Idea.all
    @all_ranks = Idea.find(Like.group(:idea_id).order('count(idea_id) desc').limit(10).pluck(:idea_id))
  end

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.create(idea_params)
    redirect_to ideas_path
  end

  def destroy
    idea = Idea.find(params[:id])
    idea.destroy
  end

  def show
    @idea = Idea.find(params[:id])
    @like = Like.new
    @comment = Comment.new
    @comments = @idea.comments.includes(:user)
  end

  def search
    @ideas = Idea.search(params[:keyword])
    respond_to do |format|
      format.html
      format.json
    end
  end

  private  
  def idea_params
    params.require(:idea).permit(:title, :info, :price).merge(user_id: current_user.id)
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.create(idea_id: params[:idea_id])
    
  end

  def destroy
    like = current_user.likes.find_by(idea_id: params[:idea_id], user_id: current_user.id)
    like.destroy
  end

  def set_variables
    @idea = Idea.find(params[:idea_id])
    @id_name = "#like-link-#{@idea.id}"
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    user = User.find(params[:relationship][:follow_id])
    following = current_user.follow(user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user
    end
  end

  def destroy
    user = User.find(params[:relationship][:follow_id])
    following = current_user.unfollow(user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to user
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @all_ranks = User.find(Like.group(:user_id).order('count(user_id) desc').limit(3).pluck(:user_id))
  end

  def show
    @user = User.find(params[:id])
    @ideas = @user.ideas
  end

  def edit
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "ユーザー情報を編集しました。"
      redirect_to("/")
    else
      flash.now[danger] = "ユーザー情報の編集に失敗しました。"
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
%h4 Comments Index
-if @comments
  -@comments.each do |comment|
    %p
      %strong
        =link_to comment.user.name, "/users/#{comment.user_id}"
      = comment.text

app/views/comments/create.js.erb
$('.comments').html("<%= escape_javascript(render 'comments', comments: @comments) %>");
$('.comment-form').html("<%= escape_javascript(render 'comment_form', comment: @comment) %>");

app/views/ideas/_header.html.haml
.header
  .header__info
    .header--logo
      %a(href="/")
        Idea-Maker
    .header--user
      -if user_signed_in?
        .header--user_name
          User Name:
          =current_user.name
  .header--weather
    =@city_telop
  .header--btn
    -# -if user_signed_in?
    .header--btn--logout
      = link_to " Logout", destroy_user_session_path ,class:"btn logout", method: :delete
    .header--btn--create
      = link_to "Post", new_idea_path , class: "btn create"
    %a(href="/users" class="header--btn--users btn")
      =icon("fas", "users")
    %a(href="/users/edit" class="header--btn--icon btn")
      =icon("fas", "cog")

    -# -else
    -#   .header--btn--login
    -#     = link_to "ログイン", new_user_session_path, class:"btn login"
    -#   .header--btn--new
    -#     = link_to "新規登録" , new_user_registration_path, class:"btn registration"
    -#   %a(href="/users" class="header--btn--users btn")
    -#     =icon("fas", "users")

app/views/ideas/_main_idea.html.haml
.html
  = render "header"
  .header-search
    =form_with(url: search_ideas_path, local: true, method: :get, class:"search-form") do |f|
      =f.text_field :keyword, placeholder: "Search", class: "search-input"
      -# =f.submit "Search", class: "search-btn"
  .body-logo
    ALL OF IDEAS
  .body
    -# ideaのブロックでひとかたまりのアイデア
    .ideas
      -@ideas.reverse_each do |idea|
        -# -if user_signed_in? 
        %a(href="/ideas/#{idea.id}" class="idea")
          .idea--title
            = idea.title
            -# idea-infoでユーザ名と値段の情報を持つ
          .idea--info 
            .idea--info--user_name
              = idea.user.name
            .idea--info--price
              price: $
              = idea.price
        -# -else
        -#   .idea--title
        -#     = idea.title
        -#     -# idea-infoでユーザ名と値段の情報を持つ
        -#   .idea--info 
        -#     .idea--info--user_name
        -#       = idea.user.name
        -#     .idea--info--price
        -#       price: $
        -#       = idea.price
      %end


    .body-ranking
      Now the hottest Idea!
      .body-ranking-ideas
        -@all_ranks.each do |idea|
          = idea.title

    .google-maps
      会社位置
      #map
      %script{type:"text/javascript",src:"code1_1.js"}
      %script{src:"https://maps.googleapis.com/maps/api/js?key=AIzaSyDucSCzl_8X4EUv7XDnNBnsM2sAiUtWUG4&language=ja&callback=initMap"}

app/views/ideas/index.html.haml
.wrapper
  = render "main_idea"

app/views/ideas/new.html.haml
.content
  =render "header"
  .form
    %h2.form--logo
      Let's Show Your Idea!!
    =form_for @idea do |f|
      =f.text_field :title, class:"form--title form-color", placeholder:"Title"
      .form--box
      =f.text_area :info, class:"form--info form-color", placeholder:"Tell Me Your Special Idea!"
      =f.number_field :price, class:"form--price form-color", min:1, placeholder:"Input Your Idea's Worth($)"
      =f.submit "Send", class:"form--btn"

app/views/ideas/search.html.haml
.wrapper
  .html
  = render "header"
  .header-search
    =form_with(url: search_ideas_path, local: true, method: :get, class:"search-form") do |f|
      =f.text_field :keyword, placeholder: "Search", class: "search-input"
      =f.submit "Search", class:"search-btn"
      -# =f.submit "Search", class: "search-btn"
  .body-logo
    ALL OF IDEAS
  .body
    -# ideaのブロックでひとかたまりのアイデア
    .ideas
      -@ideas.each do |idea|
        -if user_signed_in? 
          %a(href="/ideas/#{idea.id}" class="idea")
            .idea--title
              = idea.title
              -# idea-infoでユーザ名と値段の情報を持つ
            .idea--info 
              .idea--info--user_name
                = idea.user.name
              .idea--info--price
                price: $
                = idea.price
        -else
          .idea--title
            = idea.title
            -# idea-infoでユーザ名と値段の情報を持つ
          .idea--info 
            .idea--info--user_name
              = idea.user.name
            .idea--info--price
              price: $
              = idea.price
      %end

app/views/ideas/show.html.haml
.idea-wrapper
  =render "header"
  .idea-wrapper__logo
    IDEA INFORMATION
  .idea-wrapper__info
    .idea-wrapper__info--title
      title: 
      = @idea.title
    .idea-wrapper__info--name
      name: 
      = @idea.user.name
    .idea-like#like-link{ id: @idea.id }
      Like: 
      %h3
        =@idea.likes.count
      =render 'likes/like', collection: @ideas, as: :idea
  .idea-wrapper__box
    .idea-wrapper__box__content
      =@idea.info
  .idea-container
    %h2 Comments
  .comment-form
    =form_with model: [@idea, @comment], remote: true do |form|
      .idea-container-form
        =form.text_area :text, placeholder: "exchange your ideas!!", rows: "2"
        =form.submit "SEND", class:"comment-form-btn"
    .comments
      = render partial: "comments/comment"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title IdeaMaker2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/likes/_like.html.haml
-if current_user.already_liked?(@idea)
  =link_to idea_like_path(@idea.id), method: :delete, remote: true do
    =icon("fas", "heart")
-else
  =link_to idea_likes_path(@idea.id) ,method: :post, remote: true do
    =icon("far", "heart")

app/views/likes/create.js.erb
$('<%= @id_name %>').html("<%= escape_javascript(render partial: 'likes/like', locals: {idea: @idea}) %>");

app/views/likes/destroy.js.erb
$('<%= @id_name %>').html("<%= escape_javascript(render partial: 'likes/like', locals: {idea: @idea}) %>");

app/views/relationships/_follow_button.html.haml
- unless current_user == user
  - if current_user.following?(user)
    = form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'Following', class: 'follow-now'
  - else
    = form_for(current_user.relationships.build) do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit 'Follow', class: 'follows'

app/views/users/index.html.haml
.user_index
  =render "ideas/header"
  .header-search
    Search
  .user
    .user-logo
      Idea Makers
    -# ideaのブロックでひとかたまりのアイデア
    .user__belt
      -@users.each do |user| 
        %a(href="/users/#{user.id}" class="user__belt--info")
          %img(src="#{user.image}" class="icon_image")/
          = user.name
    .new-user-logo
      Ranking
      .new-user-index
        -@all_ranks.each do |user|
          =user.name

app/views/users/show.html.haml
.user-show
  =render "ideas/header"
  .user-info
    =@user.name
  .user-follow
    =render 'relationships/follow_button', user: @user
  .user-idea
    %h3.user-idea__index Your Special Ideas!
    %ul
      -@ideas.reverse_each do |idea|
        %li
          %a(href="/ideas/#{idea.id}" class="user-idea__index--each")
            = idea.title
      %end
    %h3.user-idea__likes Ideas You Like!
    %ul
      -@user.liked_ideas.each do |idea|
        %li
          %a(href="/ideas/#{idea.id}" class="user-idea__likes--each")
            =idea.title
    フォロー中
    -@user.followings.each do |user|
      = user.name
    フォロワー
    -@user.followers.where.not(id: current_user.id).each do |user|
      = user.name